### ISSUE TITLE
DatatablesBundle & Symfony 2.3.*

### ISSUE THREAD

**Issue by AlixBa** [LanKit/DatatablesBundle#16]
Hey :)

Is there an DatatablesBundle update planed ? I can't intall on Symfony 2.3.0 :/

Thanks,
Litz.

**Comment by ChadSikorra** [comment]
Hello! Thanks for letting me know about that...I haven't updated anything to 2.3 yet. Fixed by commit f9cadfeeef4adb152c97e88d539e69ee32512d80. I added a new tag for it too.
