### ISSUE TITLE
Fatal error: Class 'LanKit\DatatablesBundle\LanKit\DatatablesBundle\DependencyInjection\LanKitDatatablesExtension' not found

### ISSUE THREAD

**Issue by wtfred** [LanKit/DatatablesBundle#2]
Hello,

I just installed your bundle by following the documentation. Everything went fine with composer, then i registered the bundle in appKernel, then created a new action in a controller and then checked in frontend and bam ! I got a fatal error : 

Fatal error: Class 'LanKit\DatatablesBundle\LanKit\DatatablesBundle\DependencyInjection\LanKitDatatablesExtension' not found in /var/www/xxx/vendor/lankit/datatables-bundle/LanKit/DatatablesBundle/LanKitDatatablesBundle.php on line 12

Do i miss something ? Sorry if i did something stupid, and for my bad english ^^

**Comment by ChadSikorra** [comment]
Could you please update the bundle and try again? I just changed the case of the file. That's what I get for deciding to change the case of the bundle name and testing it on a Windows box... _sigh_

**Comment by wtfred** [comment]
Ok so, i updated but had to : 
- rename LanKit\DatatablesBundle\DependencyInjection\LanKitDataTablesExtension.php to LanKitDatatablesExtension.php
- rename LanKit\DatatablesBundle\Datatables\Datatable.php to DataTable.php

to get rid of the fatal error :)

Thanks for the quick answer !

**Comment by ChadSikorra** [comment]
Ok, tested from my linux server now. Think I got the last of the missed occurrences of of "DataTables" to "Datatables"...at least that's what my grep results tell me and it seems to work fine. I really need to write some tests for this bundle.

Updated master and pushed a new tag.

**Comment by ChadSikorra** [comment]
Closing since all the case-sensitivity issues should be fixed now (famous last words..). Let me know if you're still experiencing any issues.
