### ISSUE TITLE
Composer update required "doctrine/doctrine-bundle": "1.1.*"

### ISSUE THREAD

**Issue by stwe** [LanKit/DatatablesBundle#5]
My composer update error message:

lankit/datatables-bundle dev-master requires doctrine/doctrine-bundle 1.0.\* -> satisfiable by doctrine/doctrine-bundle v1.0.0.

Can only install one of: doctrine/doctrine-bundle v1.1.0, doctrine/doctrine-bundle v1.0.0.
Installation request for lankit/datatables-bundle dev-master -> satisfiable by lankit/datatables-bundle dev-master.

**Comment by ChadSikorra** [comment]
Looks like there was a recent version bump on dev-master for the Symfony Standard Edition. I tweaked composer to be a little more lenient. 0d57cc46260a0a4dfbc22468511441b18772844c
