### ISSUE TITLE
Pre-Filtering Search Results : display issue ?

### ISSUE THREAD

**Issue by wtfred** [LanKit/DatatablesBundle#8]
Hello,
When i'm using the "Pre-Filtering" function (ex: i want all "active" customers), when i got my results in the datatable, it say "filtered from xxx total entries"

Maybe i got something wrong but if i use a "pre-filter" i'd like not to know the list was filtered ?

I made a quick fix in the "getCountAllResults" function, i can make a pull request but maybe it's a wanted behaviour ?

Thanks for your time :)

**Comment by ChadSikorra** [comment]
Yeah, I was thinking about this when I implemented it. I wasn't sure what the expected behavior should be. I agree that not knowing the list was filtered should probably be the default behavior. But it should probably be able to be toggled.

**Comment by ChadSikorra** [comment]
The behavior you expected is now the default. It can be changed by using the `hideFilteredCount()` method. See commit 08b4b1e087d8f67c7392afc1f2dd7b3720d70b70. I'll have to update the docs later.

**Comment by wtfred** [comment]
Thanks you're awesome :)
